sudo: required
services:
  - docker
before_install:
  - docker build -t tanmayfordocker/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tanmayfordocker/docker-react npm run test
